// @generated by wingfoil::codegen — do not edit.
//
// Produced by running a wiring function and walking the graph it built, so
// every config here is frozen at generation time. Regenerate rather than
// editing: a hand edit is lost on the next run.
//
// Nothing detects at *runtime* that this file is stale. Guard it with a test
// that calls `codegen::check_artifact` — see that function's docs.

wingfoil::nitro! {
    fn ingest_generated(g: &GraphBuilder) -> Stream<f64> {
        let n0 = g.poll({ let venue = 7u64; move || venue_feed(venue) });
        let n1 = n0.map({ let scale = 0.5f64; move |raw: &u64| *raw as f64 * scale });
        let n2 = g.poll({ let venue = 11u64; move || venue_feed(venue) });
        let n3 = n2.map({ let scale = 2.0f64; move |raw: &u64| *raw as f64 * scale });
        let n4 = n1.join(&n3, |x: &f64, y: &f64| x + y);
        n4
    }
}
